volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql2
      - ./dev/mariadb:/docker-entrypoint-initdb.d
      - ./encryptionsetup:/etc/initencrypt
      - ${PWD}/encryptionsetup/my.cnf:/etc/mysql/my.cnf
      - ./encryptionkeys:/etc/mysql/encryption
    ports:
      - "3306:3306"